name: sekawan_media_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/portfolio/
  fonts:
    - family: courgette
      fonts:
        - asset: assets/fonts/courgette/Courgette-Regular.ttf
    - family: clash
      fonts:
        - asset: assets/fonts/clashdisplay/ClashDisplay-Variable.ttf
    - family: satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Light.otf
          weight: 200
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
          weight: 600
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
          weight: 700
    - family: satoshi-italic
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-LightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.otf
          weight: 700
          style: italic

